### ISSUE TITLE
morpheus: retry without apostrophe on failed words

### ISSUE THREAD

**Issue by balmas** [alpheios-project/morphsvc#16]
for alpheios-project/data-models#61, we want to add an exception to the valid unicode requirement and allow apostrophes to stand in for 1fbd (greek koronis) in greek text. Because we can't know for sure whether apostrophe is meant as an apostrophe or not, if we let them in we should have an option retry without them if the parser fails.

**Comment by monzug** [comment]
I added few words with accent at beginning or at the end to the local test file. it works as described. I am very enthusiastic of this feature.
e.g.  νέος'   'μοι     πλατύς'  added an accent, morphology shows the correct output

I did also add an extra accent to δ'' and got lexical query produced no results (same as lookup)
